from collections.abc import Iterable, Sequence
from fractions import Fraction
from os import PathLike
from typing import Any, Protocol, TypeAlias, TypeVar

__version__: str
_LiteralLike: TypeAlias = int | Literal
_Rational: TypeAlias = int | Fraction
_T = TypeVar("_T")

class ConsumedCircuitError(RuntimeError): ...
class ResourceLimitError(RuntimeError): ...

class Vtree:
    @staticmethod
    def balanced(n: int) -> Vtree: ...
    @staticmethod
    def balanced_over(variables: Sequence[int]) -> Vtree: ...
    @staticmethod
    def linear(variables: Sequence[int]) -> Vtree: ...
    @staticmethod
    def leaf(variable: int) -> Vtree: ...
    @staticmethod
    def join(left: Vtree, right: Vtree) -> Vtree: ...
    @staticmethod
    def from_text(text: str) -> Vtree: ...
    @property
    def variables(self) -> list[int]: ...
    def to_text(self) -> str: ...
    def to_dot(self) -> str: ...
    def clear_scratch(self) -> None: ...

class Literal:
    def __init__(self, variable: int, sign: bool = True) -> None: ...
    @property
    def variable(self) -> int: ...
    @property
    def sign(self) -> bool: ...
    def __invert__(self) -> Literal: ...
    def __int__(self) -> int: ...

class Limits:
    def __init__(self, *, memory_bytes: int | None = None,
                 output_nodes: int | None = None, timeout: float | None = None) -> None: ...

class Algebra(Protocol[_T]):
    def zero(self) -> _T: ...
    def leaf(self, variable: int, sign: bool | None) -> _T: ...
    def add(self, a: _T, b: _T) -> _T: ...
    def mul(self, a: _T, b: _T) -> _T: ...

class Circuit:
    @property
    def is_consumed(self) -> bool: ...
    @property
    def vtree(self) -> Vtree: ...
    def copy(self) -> Circuit: ...
    def __copy__(self) -> Circuit: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Circuit: ...
    def __and__(self, other: Circuit) -> Circuit: ...
    def __or__(self, other: Circuit) -> Circuit: ...
    def __xor__(self, other: Circuit) -> Circuit: ...
    def __invert__(self) -> Circuit: ...
    def negate(self, *, limits: Limits | None = None) -> Circuit: ...
    def condition(self, literals: Iterable[_LiteralLike], *, limits: Limits | None = None) -> Circuit: ...
    def exists(self, variables: Sequence[int], *, limits: Limits | None = None) -> Circuit: ...
    def rename(self, mapping: dict[int, int], *, limits: Limits | None = None) -> Circuit: ...
    def minimize(self, *, limits: Limits | None = None) -> Circuit: ...
    def update(self, *, insert: Iterable[Iterable[_LiteralLike]] | None = None,
               remove: Iterable[Iterable[_LiteralLike]] | None = None,
               limits: Limits | None = None) -> Circuit: ...
    def model_count(self, *, limits: Limits | None = None) -> int: ...
    def projected_model_count(self, variables: Sequence[int], *, limits: Limits | None = None) -> int: ...
    def is_sat(self, *, limits: Limits | None = None) -> bool: ...
    def equivalent(self, other: Circuit, *, limits: Limits | None = None) -> bool: ...
    def implies(self, other: Circuit, *, limits: Limits | None = None) -> bool: ...
    def support(self, *, limits: Limits | None = None) -> list[int]: ...
    def implied_literals(self, *, limits: Limits | None = None) -> list[Literal]: ...
    def satisfying_assignment(self, *, limits: Limits | None = None) -> list[Literal] | None: ...
    def weighted_count(self, weights: dict[int, tuple[_Rational, _Rational]], *, limits: Limits | None = None) -> Fraction: ...
    def evaluate(self, algebra: Algebra[_T]) -> _T: ...
    def counter(self) -> Counter: ...
    def evaluator(self, weights: dict[int, tuple[_Rational, _Rational]]) -> Evaluator: ...
    def node_count(self) -> int: ...
    def pair_count(self) -> int: ...
    def node_sizes(self) -> list[tuple[int, int, int]]: ...
    def to_bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(vtree: Vtree, data: bytes) -> Circuit: ...
    def save(self, path: str | PathLike[str]) -> None: ...
    @staticmethod
    def load(vtree: Vtree, path: str | PathLike[str]) -> Circuit: ...
    def to_dot(self) -> str: ...

class Counter:
    def observe(self, literals: Iterable[_LiteralLike]) -> None: ...
    def clear(self, variable: int) -> None: ...
    def clear_observations(self) -> None: ...
    def model_count(self, *, limits: Limits | None = None) -> int: ...
    def finish(self) -> Circuit: ...

def literal(vtree: Vtree, value: _LiteralLike, *, limits: Limits | None = None) -> Circuit: ...
def cube(vtree: Vtree, literals: Iterable[_LiteralLike], *, limits: Limits | None = None) -> Circuit: ...
def clause(vtree: Vtree, literals: Iterable[_LiteralLike], *, limits: Limits | None = None) -> Circuit: ...
def one(vtree: Vtree) -> Circuit: ...
def zero(vtree: Vtree) -> Circuit: ...
def from_models(vtree: Vtree, variables: Sequence[int], rows: Iterable[Sequence[bool]], *, limits: Limits | None = None) -> Circuit: ...
def and_(left: Circuit, right: Circuit, *, limits: Limits | None = None) -> Circuit: ...
def or_(left: Circuit, right: Circuit, *, limits: Limits | None = None) -> Circuit: ...
def xor(left: Circuit, right: Circuit, *, limits: Limits | None = None) -> Circuit: ...
def ite(condition: Circuit, then_branch: Circuit, else_branch: Circuit, *, limits: Limits | None = None) -> Circuit: ...
def or_many(circuits: Iterable[Circuit], *, limits: Limits | None = None) -> Circuit: ...
def and_exists(left: Circuit, right: Circuit, variables: Sequence[int], *, limits: Limits | None = None) -> Circuit: ...


class Evaluator:
    def observe(self, literals: Iterable[int | Literal]) -> None: ...
    def clear(self, variable: int) -> None: ...
    def clear_observations(self) -> None: ...
    def set_weights(self, weights: dict[int, tuple[_Rational, _Rational]]) -> None: ...
    def value(self, *, limits: Limits | None = None) -> Fraction: ...
    def finish(self) -> Circuit: ...
